version: '3.8'
  
services:

  app:
    image: devfiap/python-flask-app:0.1
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    networks:
       monitoring:
       
  prometheus:
    image: prom/prometheus:v2.33.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - 80:9090
    networks:
       monitoring:

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
       monitoring:

networks:
  monitoring:
     name: monitoring
