#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  
write_files:
-   content: |
        # /etc/systemd/system/node-exporter.service
        [Unit]
        Description=node-exporter
        After=docker.service
        Wants=docker.service

        [Service]
        Restart=always
        RestartSec=10s
        ExecStartPre=-/usr/bin/docker rm node-exporter
        ExecStart=/usr/bin/docker run \
                  --name node-exporter \
                  --net host \
                  --volume /run:/run \
                  --volume /proc:/host/proc:ro \
                  --volume /sys:/host/sys:ro \
                  prom/node-exporter:v1.3.1

        ExecStop=/usr/bin/docker stop node-exporter
        ExecStopPost=/usr/bin/docker rm node-exporter

        [Install]
        WantedBy=multi-user.target
    path: /etc/systemd/system/node-exporter.service

-   content: |
        # /etc/systemd/system/mediawiki.service
        
        [Unit]
        Description=Mediawiki
        After=docker.service
        Wants=docker.service
        
        [Service]
        Restart=always
        RestartSec=10s
        ExecStartPre=-/usr/bin/docker rm mediawiki
        ExecStart=/usr/bin/docker run \
                  --name mediawiki \
                  --net host \
                  mediawiki:stable
        ExecStop=/usr/bin/docker stop mediawiki
        ExecStopPost=/usr/bin/docker rm mediawiki
        
        [Install]
        WantedBy=multi-user.target
    path: /etc/systemd/system/mediawiki.service

  
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl dameon-reload
  - systemctl start docker && systemctl enable docker
  - systemctl start mediawiki && systemctl enable mediawiki
  - systemctl start node-exporter && systemctl enable node-exporter