#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker && systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - git clone https://github.com/fiapdevops/automation /home/ubuntu/automation
  - chown -R ubuntu:ubuntu /home/ubuntu/automation
  - sudo /usr/local/bin/docker-compose -f /home/ubuntu/automation/prometheus/docker-compose.yml up -d