#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  
write_files:
-   content: |
        # /etc/systemd/system/nginx.service
        
        [Unit]
        Description=nginx
        After=docker.service
        Wants=docker.service
        
        [Service]
        Restart=always
        RestartSec=10s
        ExecStartPre=-/usr/bin/docker rm nginx
        ExecStart=/usr/bin/docker run \
                  --name nginx \
                  --net host \
                  nginx:stable
        ExecStop=/usr/bin/docker stop nginx
        ExecStopPost=/usr/bin/docker rm nginx
        
        [Install]
        WantedBy=multi-user.target
    path: /etc/systemd/system/nginx.service
  
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y && apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl dameon-reload
  - systemctl start docker && systemctl enable docker
  - systemctl start nginx && systemctl enable nginx